### ISSUE TITLE
[REQUEST] just a simple example

### ISSUE THREAD

**Issue by lewislepton** [wighawag/imagesheet#1]
eeerrrrrr. yeah. that thing ;)

**Comment by wighawag** [comment]
You can see usage here : https://github.com/wighawag/spriterkha/blob/master/Sources/spriterkha/SpriterG2.hx#L12

but basically it just parse the info present in the json outputed by texture packer. I can add some comment on the field name to make it more clear

**Comment by wighawag** [comment]
Just added some comment, let me know if that suffice : https://github.com/wighawag/imagesheet/commit/62115c100e90e9ce78ff009dfd7e39e66ef59b0e

**Comment by lewislepton** [comment]
cool spot. will have a check. was wondering on if its like `FastFloat`, where you just have to import it, and it magically runs. but should be fine. thanks ;)
