### ISSUE TITLE
does this still work?

### ISSUE THREAD

**Issue by Fuzzipede** [wighawag/imagesheet#2]
I try to use SpriterKha and it doesn't work. 
When I load ImageSheet with fromTexturePackerJsonArray() everything seems fine. The Array<Dynamic> frames gets filled. I can see 10 subimages, but the for-loop just gets skipped. I do not understand it. Can you help me? Thanks for the great work anyway. The debug does work. 👍

**Comment by Fuzzipede** [comment]
never mind it was exporting issue.  I had to check "Use list style json file".

**Comment by wighawag** [comment]
Cool, good to know there is no problem. I should maybe add some
documentation though.
